// src/context/KubeConfigContext.tsx
"use client";
import React, { createContext, useState, useContext, ReactNode } from 'react';
import Cookies from 'js-cookie';

interface KubeConfigContextProps {
  kubeconfig: string | null;
  setKubeconfig: (config: string | null) => void;
}

const KubeConfigContext = createContext<KubeConfigContextProps | undefined>(undefined);

export const KubeConfigProvider = ({ children }: { children: ReactNode }) => {
  const initialKubeconfig = Cookies.get('kubeconfig') ? Cookies.get('kubeconfig') : null;
  const [kubeconfig, setKubeconfigState] = useState<string | null>(initialKubeconfig);

  const setKubeconfig = (config: string | null) => {
    setKubeconfigState(config);
    if (config) {
      Cookies.set('kubeconfig', config, { expires: 7 });
    } else {
      Cookies.remove('kubeconfig');
    }
  };

  const value: KubeConfigContextProps = {
    kubeconfig,
    setKubeconfig,
  };

  return (
    <KubeConfigContext.Provider value={value}>
      {children}
    </KubeConfigContext.Provider>
  );
};

export const useKubeConfig = (): KubeConfigContextProps => {
  const context = useContext(KubeConfigContext);
  if (context === undefined) {
    throw new Error('useKubeConfig must be used within a KubeConfigProvider');
  }
  return context;
};
```
```typescript
// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { KubeConfigProvider } from "@/context/KubeConfigContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Namespace Git Transfer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <KubeConfigProvider>
          {children}
        </KubeConfigProvider>
      </body>
    </html>
  );
}